<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kuliner_model extends CI_Model
{

    public $table = 'tbl_kuliner';
    public $id = 'id_kuliner';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

  function get_coordinates()    {
        $return = array();
        $this->db->select("lat,lng,nama_kuliner,images");
        $this->db->from("tbl_kuliner");
        $query = $this->db->get();
        if ($query->num_rows()>0) {
         foreach ($query->result() as $row) {
            array_push($return, $row);
         }
    }
        return $return;
    } 

    // function get_maps_id($id){
    //    $id= $this->uri->segmen
    // }

     public function pdf($id)
    {
       $id            = $this->uri->segment(3);
       $data['suratlembur'] = $this->db->get_where('tbl_surat_lembur', array('id_sl' => $id))->row_array(); 
        ini_set('memory_limit', '32M');
        $html = $this->load->view('surat_lembur/tbl_surat_lembur_pdf', $data, true);
        $this->load->library('pdf');
        $pdf = $this->pdf->load();
        $pdf->WriteHTML($html);
        $pdf->Output('tbl_surat_lembur.pdf','I'); 
    }



    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_kuliner', $q);
	$this->db->or_like('nama_kuliner', $q);
	$this->db->or_like('id_kategori', $q);
    $this->db->or_like('alamat', $q);
	$this->db->or_like('images', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('lat', $q);
	$this->db->or_like('lng', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_kuliner', $q);
	$this->db->or_like('nama_kuliner', $q);
     $this->db->join('tbl_kategori','tbl_kategori.id_kategori=tbl_kuliner.id_kategori');
	 // $this->db->or_like('id_kategori', $q);
     $this->db->or_like('alamat', $q);
	$this->db->or_like('images', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('lat', $q);
	$this->db->or_like('lng', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kuliner_model.php */
/* Location: ./application/models/Kuliner_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-08-07 16:56:48 */
/* http://harviacode.com */